### ISSUE TITLE
Filepath initializes as empty string

### ISSUE THREAD

**Issue by nynhex** [jrobertson/saytime#1]
When installing this gem and running it from IRB this is the result:

````
irb(main):001:0> require 'saytime'
=> true
irb(main):002:0> time = Saytime.new
=> #<Saytime:0x007f99db80a260 @filepath="">
irb(main):003:0> time.now
Errno::ENOENT: No such file or directory - play
	from /Users/nynhex/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/saytime-0.2.1/lib/saytime.rb:34:in ``'
	from /Users/nynhex/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/saytime-0.2.1/lib/saytime.rb:34:in `now'
	from (irb):3
	from /Users/nynhex/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'
````

In the initialize method it's calling `@filepath = filepath` with the initialize argument being empty.  Would this be better served initializing the `wav` directory in a static location or even in the user's home dir `~/home/username/wave`.

The other options is to use some sort of input whether it's `gets` or `ARGV` from the cli to specify the path.

Just a random observation, you may still be working on this one but figured I'd let you know I'm having problems.  Would be happy to help in development.

**Comment by jrobertson** [comment]
You need to `apt-get install sox`. After that the `play` program should be available to run from the saytime gem, assuming you are using a Debian based operating system  e.g. Ubuntu

**Comment by nynhex** [comment]
@jrobertson Actually I'm on Darwin (MacOS) but I can try installing sox with brew.  This would be nice if the project could be cross-platform.  Neat little gem you came up with.
